# Generated by Django 5.1.7 on 2025-09-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('current_skills', models.TextField(blank=True, null=True)),
                ('current_job', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.CharField(blank=True, choices=[('<3L', 'Less than 3 LPA'), ('3-6L', '3-6 LPA'), ('6-10L', '6-10 LPA'), ('10L+', 'More than 10 LPA')], max_length=10, null=True)),
                ('dream_role', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
