# Generated by Django 5.1.7 on 2025-10-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_profile_image_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('skills', models.ManyToManyField(related_name='dream_role', to='core.skill')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='dream_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dreamrole'),
        ),
    ]
