# Generated by Django 5.1.7 on 2025-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dreamrole_alter_profile_dream_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_salary',
            field=models.CharField(blank=True, choices=[('--', 'Unemployed/Unpaid Intern'), ('<3L', 'Less than 3 LPA'), ('3-6L', '3-6 LPA'), ('6-10L', '6-10 LPA'), ('10L+', 'More than 10 LPA')], max_length=10, null=True),
        ),
    ]
